### ISSUE TITLE
Issue while hitting the Terravibes REST API to run a workflow

### ISSUE THREAD

**Issue by click2cloud-Nagaraj** [microsoft/project-terravibes#105]
Hello team,
We have been seeing an error "invalid datetime format", while trying to run a workflow through Rest API (Terravibes Create Run) with the default Helloworld request body.
PFB the Response body for the same,

![Screenshot 2023-06-06 180548](https://github.com/microsoft/farmvibes-ai/assets/101167141/8b60e678-01e8-4497-9347-aae32667eda2)

**Comment by click2cloud-Nagaraj** [comment]
Sure @rafaspadilha ,
This was the case since the latest release, earlier it was working fine and even rn Python Client works as expected to run a workflow, So this doesn't happen with the Python Client.
I have tried consuming the Terravibes Create Run POST API in a couple of ways,
* First, through UI at "http://<cluster_addr>:<port>/v0/docs/", where the request body would look like

Request Body :
```
{
  "name": "example workflow run for sample region",
  "workflow": "helloworld",
  "parameters": {},
  "user_input": {
    "start_date": "2021-02-02",
    "end_date": "2021-08-02",
    "geojson": {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "geometry": {
            "type": "Polygon",
            "coordinates": [
              [
                [
                  -88.068487,
                  37.058836
                ],
                [
                  -88.036059,
                  37.048687
                ],
                [
                  -88.012895,
                  37.068984
                ],
                [
                  -88.026622,
                  37.085711
                ],
                [
                  -88.062482,
                  37.081461
                ],
                [
                  -88.068487,
                  37.058836
                ]
              ]
            ]
          }
        }
      ]
    }
  }
}

```
And the Response Body generated was :
```
{
  "detail": [
    {
      "loc": [
        "body",
        "start_date"
      ],
      "msg": "invalid datetime format",
      "type": "value_error.datetime"
    },
    {
      "loc": [
        "body",
        "end_date"
      ],
      "msg": "invalid datetime format",
      "type": "value_error.datetime"
    }
  ]
}
```

* Second, consuming the same POST API to run a workflow, in Golang code with the similar input as mentioned in the above request body, which ended up with the same error.

So, this issue might be due to a change in the datatype of start_date, end_date and the way they are being parsed, in the latest version

**Comment by zaned897** [comment]
The issue does not seem to be a change in data type, but rather the format of the date. I have been able to use the API by adding the time to the date:
```

{
  "name": "example workflow run for sample region",
  "workflow": "helloworld",
  "parameters": {},
  "user_input": {
    "start_date": "2021-02-02T10:00:00",
    "end_date": "2021-08-02T18:30:00",
    "geojson": {
...
```

**Comment by rafaspadilha** [comment]
We changed how the input was parsed in the API in a previous release and missed updating the run submission example. 
We have updated the example with the correct date format. This will be reflected in the next release.
 
Thanks @click2cloud-Nagaraj for raising this issue and @zaned897 for pointing that out.
